Fix multiple 2019 sdk problems

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -149,12 +149,22 @@ matrix:
         - clang-3.8
   # fbx2019
   - os: linux
-    compiler: gcc
+    compiler: gcc-6
+    addons:
+      apt:
+        sources:
+        - ubuntu-toolchain-r-test
+        packages:
+        - g++-6
     env:
+      - env_build_cpp11=1
+      - env_cmake_cxx_compiler=g++-6
+      - env_cmake_c_compiler=gcc-6
       - fbx_download=https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/20192/fbx20192_fbxsdk_linux.tar.gz
   - os: osx
     compiler: clang
     env:
+      - env_build_cpp11=1
       - fbx_download=https://www.autodesk.com/content/dam/autodesk/www/adn/fbx/20192/fbx20192_fbxsdk_clang_mac.pkg.tgz
 
 before_install:
@@ -167,13 +177,17 @@ install:
     sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev;
   fi
 # Download and install fbx sdk
+# "|| true" because 2019 sdk would return code 130 when reading the readme (lol)
+# chmod because fbx2019 will install with 700
 - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
-    FBX_DOWNLOAD=${fbx_download:-"http://download.autodesk.com/us/fbx/2017/2017.1/fbx20171_fbxsdk_linux.tar.gz"}
+    FBX_DOWNLOAD=${fbx_download:-"http://download.autodesk.com/us/fbx/2017/2017.1/fbx20171_fbxsdk_linux.tar.gz"};
     mkdir fbx;
     cd fbx;
     sudo wget $FBX_DOWNLOAD -O fbx.tar.gz;
     sudo tar -xf "fbx.tar.gz";
-    yes yes | sudo ./*_fbxsdk_linux /usr/local;
+    (yes yes | sudo ./*_fbxsdk_linux /usr/local) || true;
+    sudo chmod -R 755 /usr/local/lib
+    sudo chmod -R 755 /usr/local/include
     cd ..;
   fi
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
